### PR TITLE
fix flaky `installation_repositories added` test from `TestHandleGitHubAppWebHook`

### LINKED ISSUE #4710: `installation_repositories added` test from `TestHandleGitHubAppWebHook` is flaky
### Describe the issue

Every once in a while we'll get an error that looks as follows:
```
2024-10-10T06:24:43.4241521Z === CONT  TestAll/TestHandleGitHubAppWebHook/installation_repositories_added
2024-10-10T06:24:43.4243131Z     passthroughqueue.go:49: Passing message through queue: 019cc289-dca4-4f7f-b3a4-b37182a1af62
2024-10-10T06:24:43.4244223Z     handlers_githubwebhooks_test.go:3588: 
2024-10-10T06:24:43.4245881Z         	Error Trace:	/home/runner/work/minder/minder/internal/controlplane/handlers_githubwebhooks_test.go:3334
2024-10-10T06:24:43.4248564Z         	            				/home/runner/work/minder/minder/internal/controlplane/handlers_githubwebhooks_test.go:3588
2024-10-10T06:24:43.4249726Z         	Error:      	Not equal: 
2024-10-10T06:24:43.4250603Z         	            	expected: "stacklok/minder"
2024-10-10T06:24:43.4251609Z         	            	actual  : "stacklok/trusty"
2024-10-10T06:24:43.4252307Z         	            	
2024-10-10T06:24:43.4252938Z         	            	Diff:
2024-10-10T06:24:43.4253704Z         	            	--- Expected
2024-10-10T06:24:43.4254383Z         	            	+++ Actual
2024-10-10T06:24:43.4255110Z         	            	@@ -1 +1 @@
2024-10-10T06:24:43.4255889Z         	            	-stacklok/minder
2024-10-10T06:24:43.4256648Z         	            	+stacklok/trusty
2024-10-10T06:24:43.4257833Z         	Test:       	TestAll/TestHandleGitHubAppWebHook/installation_repositories_added
```

This is because the test issues two events, one for the `stacklok/minder` and another one for the `stacklok/trusty` event.

Since the test checks for the name of one of them, the test has a 50% probability of failure.

### To Reproduce

_No response_

### What version are you using?

_No response_

### PR DESCRIPTION
**Pull request by JAORMX**
# Summary

This allows for either message to be parsed first.

Fixes #4710

## Change Type

***Mark the type of change your PR introduces:***

- [x] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [ ] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

***Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.***

# Review Checklist:

- [x] Reviewed my own code for quality and clarity.
- [x] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

File: internal/controlplane/handlers_githubwebhooks_test.go [hunk 1]
```diff
@@ -3331,7 +3331,9 @@ func (s *UnitTestSuite) TestHandleGitHubAppWebHook() {
 				require.Equal(t, providerID, evt.ProviderID)
 				require.Equal(t, projectID, evt.ProjectID)
 				require.Equal(t, v1.Entity_ENTITY_REPOSITORIES, evt.EntityType)
-				require.Equal(t, "stacklok/minder", evt.Properties[properties.PropertyName])
+
+				// the name can be either stacklok/minder or stacklok/trusty
+				require.Contains(t, []string{"stacklok/minder", "stacklok/trusty"}, evt.Properties[properties.PropertyName])
```
Comment (blkt) [inline internal/controlplane/handlers_githubwebhooks_test.go:3336]: **question:** I think the change is fine, we don't care about the order here, but I am curious, do you know why this happens?

We use go channels in these tests as backend for Watermill, which should guarantee order, so there must be something that randomly switches order in the caller, I guess. Maybe some data structure?

**Review by blkt — APPROVED** [review]

File: internal/controlplane/handlers_githubwebhooks_test.go (hunk 1 above)
Comment (JAORMX) [reply internal/controlplane/handlers_githubwebhooks_test.go:3336]: I'm not sure yet. There are two options:
* we're getting packages in an unordered fashion for some reason (some map iteration maybe? these are unordered in golang).
* we're losing a message.

Either way, we should probably add an assertion about the amount of messages processed if we haven't yet.
