### PR TITLE
Include rule name in PR branch name to avoid collisions

### LINKED ISSUE #2350: PR "from" branch only uses rule type to generate the name
### Describe the issue

When opening a PR, we need to open a PR from a branch. We derive the name of the branch from the "title" of the PR in the rule type, but that doesn't work well if we have two rules using the same rule type unless there's something temptable in the title. We should take the name of the rule into account as well.

### To Reproduce

Create a profile that uses two codeql rules, see them race.

### What version are you using?

_No response_

### PR DESCRIPTION
**Pull request by krrish175-byte**
# Summary

When a profile uses two rules that share the same rule type, the PR remediation engine derives the "from" branch name solely from the rule type's title template. This causes both rules to generate identical branch names and race each other — whichever runs second overwrites the first's branch and no separate PR is opened for it.

This fix incorporates the rule instance name into the branch name:

- With a rule name: `minder_<rule-name>_<normalized-title>`
- Without a rule name (empty/legacy): `minder_<normalized-title>` (backward compatible)

No dependencies required.

Fixes #2350

# Testing

- Added `TestBranchBaseName` unit tests covering:
  - Empty rule name falls back to the old format (backward compatibility)
  - Rule name is included when present
  - Two rules with the same title but different names produce distinct branch names
- All existing `TestPullRequestRemediate` table-driven tests updated to pass the rule name argument and continue to pass

### CODE REVIEW

File: internal/engine/actions/remediate/pull_request/pull_request_test.go [hunk 1]
```diff
@@ -699,3 +699,49 @@ func TestPullRequestRemediate(t *testing.T) {
 		})
 	}
 }
+
+func TestBranchBaseName(t *testing.T) {
```
Comment (evankanderson) [inline internal/engine/actions/remediate/pull_request/pull_request_test.go]: Can we extend `TestPullRequestRemediate` to check the rulename case, rather than adding a smaller test?  I'd prefer to have somewhat larger tests that check the integration area between the smaller functions, rather than testing the small functions and then *also* needing to test the larger outer surface area.

**Review by evankanderson — COMMENTED** [review]
This looks good.  One comment on the tests -- if it turns out to be seriously painful, please flag it rather than toiling a lot for this particular preference.

File: internal/engine/actions/remediate/pull_request/pull_request_test.go [hunk 2]
```diff
@@ -699,3 +727,4 @@ func TestPullRequestRemediate(t *testing.T) {
 		})
 	}
 }
+
```
Comment (evankanderson) [inline internal/engine/actions/remediate/pull_request/pull_request_test.go]: Lint doesn't like the extra newline at the end of the file.  (And we need to fix it, or lint will trip on it for every subsequent PR.)

**Review by evankanderson — DISMISSED** [review]
One small formatting change, otherwise looks good

**Comment by krrish175-byte** [comment]
@evankanderson PTAL

**Review by evankanderson — APPROVED** [review]
