### PR TITLE
Handle rate limiting errors for GitHub API

### LINKED ISSUE #2261: Handle rate limiting errors for GitHub API
### Describe the issue

Currently, we don't handle rate limit exceeded errors from the GitHub API.  From [GitHub API Docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit):

> Continuing to make requests while you are rate limited may result in the banning of your integration.

GitHub suggests [Best practices for using the REST API](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28), which mentions handling the rate limit exceeded errors.

Discord Thread: https://discord.com/channels/1184987096302239844/1185287949240242258/1201083912521252885

- [x] Add client caching to handle rate limiting (https://github.com/stacklok/minder/pull/2271)
- [ ] Update all endpoints to handle rate-limiting errors

### To Reproduce

_No response_

### What version are you using?

main

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Issue #2261 

* We employ an optimistic concurrency control model to minimize goroutine blocking and reduce rate limit errors, thus preventing integration bans

* Each server replica maintains its own set of rate-limited clients, eliminating the need for synchronization across replicas. If a rate limit error occurs, the client self-blocks and is added to a cache for future requests

* Requests that return rate limit errors are retried following a backoff period

Note:

The current watermill pub-sub implementation being used, i.e. SQL and go channels, are both a single channel with head-of-line blocking, which means that blocking in middleware/handler blocks all processing. So, currently, if a token is blocked, the entire processing will be blocked.

This will change when we shift to other pub-sub implementations and have multiple workers.

### CODE REVIEW

File: internal/providers/github/github_rest.go [hunk 1]
```diff
@@ -609,10 +610,30 @@ func (c *RestClient) ListPullRequests(
...
+
+		// If err is of type RateLimitError or AbuseRateLimitError, don't do permanent backoff
+		if isRateLimitError(err) {
+			return err
+		}
+
+		return backoffv4.Permanent(err)
+	}
+	return performWithRetry(ctx, op)
 }
```
Comment (Vyom-Yadav) [inline internal/providers/github/github_rest.go:637]: `CreateComment` endpoint is modified as an example. If we agree on the implementation, other endpoints will be modified as well.

File: internal/providers/github/github.go [hunk 2]
```diff
@@ -115,3 +126,78 @@ func ParseV1Config(rawCfg json.RawMessage) (*minderv1.GitHubProviderConfig, erro
...
+		return nil
+	}
+
+	select {
+	case <-blockedChan:
+		return nil
+	case <-ctx.Done():
+		return ctx.Err()
+	case <-time.After(MaxRateLimitWait):
+		return fmt.Errorf("rate limit wait exceeded for %s", c.GetOwner())
```
Comment (jhrozek) [inline internal/providers/github/github.go:142]: Do you think it would be a good idea to create a timer manually and cancel it the wait finishes sooner than the timer fires to deallocate it?
```go
timer := time.NewTimer(MaxRateLimitWait)
    defer func() {
        if !timer.Stop() {
            <-timer.C
        }
    }()
```

File: internal/providers/github/github.go [hunk 3]
```diff
@@ -65,6 +74,7 @@ func NewRestClient(
 	ctx context.Context,
 	config *minderv1.GitHubProviderConfig,
 	metrics telemetry.HttpClientMetrics,
+	tokenStatStore *tokenstatus.Store,
```
Comment (jhrozek) [inline internal/providers/github/github.go:77]: reading the rest of this module sounds like `tokenstatus.Store` is now required. Is that intended? If yes, then should we error if the store is not provided?

Alternatively, I wonder if it would make sense to rather create a `WithTokenStatus` option and handle its absence in the REST code.

File: internal/tokenstatus/token_status.go [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+package tokenstatus
+
+import (
+	"sync"
+
+	"github.com/stacklok/minder/internal/db"
+)
+
+// Store stores the rate limit status of token
+type Store struct {
```
Comment (jhrozek) [inline internal/tokenstatus/token_status.go:25]: I don't have a great use-case in mind, so this might be an over engineering suggestion, but since the members of store are not exported anyway, I wonder if creating an interface and exposing it would allow for easier testing.

**Review by jhrozek — COMMENTED** [review]
I started the review, I haven't finished reading all of the PR, so I'm submitting the comments I had in the meantime and will resume the review later today.

Great work!

File: internal/tokenstatus/token_status.go [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+	status map[key]chan struct{}
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply internal/tokenstatus/token_status.go:26]: > Have you considered using `xsync.MapOf`? We already use it in minder, so you wouldn't drag in a new dependency and you wouldn't have to take care of the mutex yourself.

We use `v1.5.2` which is not supported now. and even`v3` had a bug fix a few months back:

> Fix too aggressive Map/MapOf shrinking on deletion leading to out of range panic

First of all, I'd suggest that we update the version as many bugs have been fixed since `v1.5.2`. Secondly, I'm open to using `xsync.MapOf` but I'm not too sure about the stability given that a recent version fixed a out of range panic. Wdyt?

File: internal/providers/github/github.go (hunk 2 above)
Comment (Vyom-Yadav) [reply internal/providers/github/github.go:142]: Yeah, we should stop the timer with defer for better and faster gc. How about
```go
func (c *RestClient) waitIfRateLimited(ctx context.Context) error {
	blockedChan, ok := c.tokenStatStore.GetBlockingChan(c.token, db.ProviderTypeGithub)
	if !ok {
		return nil
	}

	timer := time.NewTimer(MaxRateLimitWait)
	defer timer.Stop()

	select {
	case <-blockedChan:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return fmt.Errorf("rate limit wait exceeded for %s", c.GetOwner())
	}
}
```

File: internal/providers/github/github.go (hunk 3 above)
Comment (Vyom-Yadav) [reply internal/providers/github/github.go:77]: > reading the rest of this module sounds like tokenstatus.Store is now required. Is that intended?'

Yes, it is. I'll add a null check.

> Alternatively, I wonder if it would make sense to rather create a WithTokenStatus option and handle its absence in the REST code.

Why would it be absent? The only case where I think it may be absent is when we don't want to handle rate limit errors. Is this something we should support? For me, if we don't want to be blocked, we can pass a context with a short timeout (in case we are blocked by rate limit)

File: internal/tokenstatus/token_status.go (hunk 4 above)
Comment (Vyom-Yadav) [reply internal/tokenstatus/token_status.go:25]: I am ok with doing so, but as you said, I also don't have a use case for that. As far as testing is concerned, I think the current (main) implementation is fine, and we wouldn't need any method, unless we want to do something similar to mocking, counting method calls, which I feel is not required.

File: internal/providers/github/github_rest.go (hunk 1 above)
Comment (jhrozek) [reply internal/providers/github/github_rest.go:637]: I like this pattern, but I wonder if we can make this more generic to avoid repeating the closure around all GH calls. Taking your `CreateComment` example into account, could we do something like:
```go
func (c *RestClient) CreateComment(ctx context.Context, owner, repo string, number int, comment string) error {
    createCommentWrapper := func(ctx context.Context) (*github.Response, error) {
        return c.client.Issues.CreateComment(ctx, owner, repo, number, &github.IssueComment{
            Body: &comment,
        })
    }

    return c.rateLimitHandler(ctx, createCommentWrapper)
}
```

and then extract the closure into a non-exported function:
```go
type ghClientWrapper func(ctx context.Context) (*github.Response, error)

func (c *RestClient) rateLimitHandler(ctx context.Context, wrapper ghClientWrapper) error {
    op := func() error {
        // Check if the token is currently rate limited, block the goroutine if it is
        err := c.waitIfRateLimited(ctx)
        if err != nil {
            return err
        }

        _, resp, err := apiCall(ctx)
        if err != nil {
            rateLimCheckErr := c.checkRateLimitResponse(ctx, resp.Response)
            if rateLimCheckErr != nil {
                return rateLimCheckErr
            }

            // If err is of type RateLimitError or AbuseRateLimitError, don't do permanent backoff
            if isRateLimitError(err) {
                return err
            }

            return backoffv4.Permanent(err)
        }

        return nil
    }

    return performWithRetry(ctx, op)
}
```

File: internal/providers/github/github_rest.go [hunk 6]
```diff
@@ -623,3 +644,19 @@ func (c *RestClient) ListEmails(ctx context.Context, opts *github.ListOptions) (
...
+}
+
+func isRateLimitError(err error) bool {
+	var rateLimitError *github.RateLimitError
+	isRateLimitErr := errors.As(err, &rateLimitError)
+
+	var abuseRateLimitError *github.AbuseRateLimitError
+	isAbuseRateLimitErr := errors.As(err, &abuseRateLimitError)
+
+	return isRateLimitErr || isAbuseRateLimitErr
```
Comment (jhrozek) [inline internal/providers/github/github_rest.go:661]: can we just do:
```go
func isRateLimitError(err error) bool {
    var rateLimitError *github.RateLimitError
    var abuseRateLimitError *github.AbuseRateLimitError
    return errors.As(err, &rateLimitError) || errors.As(err, &abuseRateLimitError)
}
```

Comment (jhrozek) [reply internal/providers/github/github_rest.go:661]: although on second though, the extra boolean flags might be useful for extra debugging (I'll add another comment with better locality about that)

File: internal/providers/github/github.go [hunk 7]
```diff
@@ -115,3 +126,78 @@ func ParseV1Config(rawCfg json.RawMessage) (*minderv1.GitHubProviderConfig, erro
...
+	// Optimistic concurrency is used to avoid the overhead of a mutex lock for every request.
+	err := c.waitIfRateLimited(ctx)
+	if err != nil {
+		return err
+	}
+
+	// Check if rate limit headers are present
+	remaining, _ := strconv.Atoi(resp.Header.Get("x-ratelimit-remaining"))
+	resetTimeUnix, _ := strconv.ParseInt(resp.Header.Get("x-ratelimit-reset"), 10, 64)
+	retryAfter, _ := strconv.Atoi(resp.Header.Get("retry-after"))
```
Comment (jhrozek) [inline internal/providers/github/github.go:165]: Do you think it might be useful to log these values at a `Debug` level?

File: internal/providers/github/github.go [hunk 8]
```diff
@@ -115,3 +126,78 @@ func ParseV1Config(rawCfg json.RawMessage) (*minderv1.GitHubProviderConfig, erro
...
+	}
+
+	if retryAfter > 0 {
+		waitTime := time.Duration(retryAfter) * time.Second
+
+		logger.Warn().Msgf("Secondary rate limit exceeded by %s. Waiting for %s", c.GetOwner(), waitTime)
+		return c.blockAndWaitWithTimeout(ctx, waitTime, MaxRateLimitWait)
+	}
+
+	logger.Warn().Msgf("Rate limit exceeded by %s. Waiting for 1 minute before retrying", c.GetOwner())
```
Comment (jhrozek) [inline internal/providers/github/github.go:181]: Could we extract `1*time.Minute` to a var or a const to make sure we don't forget updating the log message if we update the wait time?

File: internal/providers/github/github.go [hunk 9]
```diff
@@ -115,3 +126,78 @@ func ParseV1Config(rawCfg json.RawMessage) (*minderv1.GitHubProviderConfig, erro
...
+		return fmt.Errorf("rate limit wait exceeded for %s", c.GetOwner())
+	}
+}
+
+func (c *RestClient) checkRateLimitResponse(ctx context.Context, resp *http.Response) error {
+	if resp.StatusCode != http.StatusForbidden && resp.StatusCode != http.StatusTooManyRequests {
+		return nil
+	}
+
+	logger := zerolog.Ctx(ctx)
```
Comment (jhrozek) [inline internal/providers/github/github.go:151]: could we extract the URL we tried to talk to to get a sense of what call was rate-limited and add that as a `Str` for the logger?

**Review by jhrozek — COMMENTED** [review]
Thank you I went through the rest of the code and left some comments. Mostly they are nits and I think this is great work.

File: internal/tokenstatus/token_status.go (hunk 4 above)
Comment (jhrozek) [reply internal/tokenstatus/token_status.go:25]: OK, let's leave it like this.

File: internal/tokenstatus/token_status.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (jhrozek) [reply internal/tokenstatus/token_status.go:26]: I don't have a great answer, I'm even surprised we were using such an old version. I don't see an issue with your implementation, I think the way you used `Lock`/`Rlock` etc is already correct and given that these are used in network traffic I'm not too concerned about lock congestion being a bottleneck.

So let's leave the code as-is and let me see about upgrading `xsync.MapOf`

File: internal/providers/github/github.go (hunk 2 above)
Comment (jhrozek) [reply internal/providers/github/github.go:142]: This looks good!

File: internal/providers/github/github.go (hunk 3 above)
Comment (jhrozek) [reply internal/providers/github/github.go:77]: To be honest I was only wondering if we could decrease the number of places where we pass the `tokenstatus.Store` by using something like the `WithTokenStatus` option and then just have a passthrough implementation as a default opt to avoid increasing the number of required parameters across the codebase. There's no functional reason.

File: internal/tokenstatus/token_status.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply internal/tokenstatus/token_status.go:26]: I wonder if dependabot catches updates when a newer version is released i.e. `yourcoolpackage/v3`.

File: internal/providers/github/github.go [hunk 10]
```diff
@@ -115,3 +126,78 @@ func ParseV1Config(rawCfg json.RawMessage) (*minderv1.GitHubProviderConfig, erro
...
+		return nil
+	case <-ctx.Done():
+		return ctx.Err()
+	case <-time.After(MaxRateLimitWait):
+		return fmt.Errorf("rate limit wait exceeded for %s", c.GetOwner())
+	}
+}
+
+func (c *RestClient) checkRateLimitResponse(ctx context.Context, resp *http.Response) error {
+	if resp.StatusCode != http.StatusForbidden && resp.StatusCode != http.StatusTooManyRequests {
```
Comment (jhrozek) [inline internal/providers/github/github.go:147]: Are there cases where `resp` might be `nil` on a fatal error in which case we'd have to just rely on the error rather then the reply? (I noticed that there's no `err` check between calling `c.client.Issues.CreateComment` and dereferencing `resp`)

```
	_, resp, err := c.client.Issues.CreateComment(ctx, owner, repo, number, &github.IssueComment{
			Body: &comment,
		})

		rateLimCheckErr := c.checkRateLimitResponse(ctx, resp.Response)
		if rateLimCheckErr != nil {
			return rateLimCheckErr
		}
```

**Comment by Vyom-Yadav** [comment]
I just noticed, that the go-github library internally also does something when it encounters rate-limiting errors (It starts sending mock responses stating you've been rate-limited). 

Let me check that out, and after that I'll address the review items.

**Comment by Vyom-Yadav** [comment]
@jhrozek So apparently, `go-github` comprehensively maintains rate limits for various GH endpoints and resources internally once the particular client hits a rate limit. 

E.g., If a req to create a comment hits the rate limit, then it would add that rate limit to that particular category store.  https://github.com/google/go-github/blob/975b2e55cec1dd1a438ed15ec605cc46113506ab/github/github.go#L1323-L1324

`go-github` will not make new requests internally until the timer expires (It does not use a timer, instead till a timestamp). The caller would get rate limiting errors from the library internally instead of GitHub i.e. it won't create repeated requests. This is a really formidable approach.

Here is some code from the lib to make more sense (https://github.com/google/go-github/blob/975b2e55cec1dd1a438ed15ec605cc46113506ab/github/github.go#L936-L990):
```go
// checkRateLimitBeforeDo does not make any network calls, but uses existing knowledge from
// current client state in order to quickly check if *RateLimitError can be immediately returned
// from Client.Do, and if so, returns it so that Client.Do can skip making a network API call unnecessarily.
// Otherwise it returns nil, and Client.Do should proceed normally.
func (c *Client) checkRateLimitBeforeDo(req *http.Request, rateLimitCategory rateLimitCategory) *RateLimitError {
	c.rateMu.Lock()
	rate := c.rateLimits[rateLimitCategory]
	c.rateMu.Unlock()
	if !rate.Reset.Time.IsZero() && rate.Remaining == 0 && time.Now().Before(rate.Reset.Time) {
		// Create a fake response.
		resp := &http.Response{
			Status:     http.StatusText(http.StatusForbidden),
			StatusCode: http.StatusForbidden,
			Request:    req,
			Header:     make(http.Header),
			Body:       io.NopCloser(strings.NewReader("")),
		}
		return &RateLimitError{
			Rate:     rate,
			Response: resp,
			Message:  fmt.Sprintf("API rate limit of %v still exceeded until %v, not making remote request.", rate.Limit, rate.Reset.Time),
		}
	}

	return nil
}

// checkSecondaryRateLimitBeforeDo does not make any network calls, but uses existing knowledge from
// current client state in order to quickly check if *AbuseRateLimitError can be immediately returned
// from Client.Do, and if so, returns it so that Client.Do can skip making a network API call unnecessarily.
// Otherwise it returns nil, and Client.Do should proceed normally.
func (c *Client) checkSecondaryRateLimitBeforeDo(req *http.Request) *AbuseRateLimitError {
	c.rateMu.Lock()
	secondary := c.secondaryRateLimitReset
	c.rateMu.Unlock()
	if !secondary.IsZero() && time.Now().Before(secondary) {
		// Create a fake response.
		resp := &http.Response{
			Status:     http.StatusText(http.StatusForbidden),
			StatusCode: http.StatusForbidden,
			Request:    req,
			Header:     make(http.Header),
			Body:       io.NopCloser(strings.NewReader("")),
		}

		retryAfter := time.Until(secondary)
		return &AbuseRateLimitError{
			Response:   resp,
			Message:    fmt.Sprintf("API secondary rate limit exceeded until %v, not making remote request.", secondary),
			RetryAfter: &retryAfter,
		}
	}

	return nil
}
```
It internally maintains when the client will be ready to make new requests. 

---

These were the features. Now the problem is that we create a new client for every request, making all that code useless. The approach we should be really following is caching the client and checking the cache for a client if it already exists. Wdyt about this approach? 

Also, if we add the client to the cache, we may want to use something more sophisticated than a map with Mutex. We cannot have a constantly growing cache. We would have to remove no longer valid tokens to avoid memory going boom. (Maybe a periodic job within the server to invalidate the cache)

**Comment by Vyom-Yadav** [comment]
We pass in context whenever we initialize the GitHub client, so I don't think caching the client with context is possible.  Instead, we can follow the approach of not passing `ctx` while creating the client. I have not checked all usages, but we are probably not passing `ctx` with a `httpClient` as a value. 

`ctx` is only used to get `ctx` client:
```go
func ContextClient(ctx context.Context) *http.Client {
	if ctx != nil {
		if hc, ok := ctx.Value(HTTPClient).(*http.Client); ok {
			return hc
		}
	}
	if appengineClientHook != nil {
		return appengineClientHook(ctx)
	}
	return http.DefaultClient
}
``` 
If we don't use Google app engine, we get the `DefaultClient`, so I think we can safely remove `ctx` while creating a new rest client. For context cancellation, `ctx` passed to rest API calls would perfectly do that task.

**Comment by Vyom-Yadav** [comment]
Other than that, I don't see any problem caching a `*http.Client`, wdyt?

**Comment by Vyom-Yadav** [comment]
After doing some research, I think we can do this. Istio also caches the HTTP client to reuse the connection in the future. https://github.com/istio/istio/blob/7bd27e8a432bd700f754e54593dc584d4973d376/pilot/cmd/pilot-agent/status/server.go#L266-L266

**Comment by jhrozek** [comment]
Thank you for doing all this research @Vyom-Yadav. Where/how were you thinking about caching the client, in the tokenStatusStore?

One thing that sounds concerning to me is that if we were to cache the http clients globally as opposed to e.g. for a single evaluation of an entity, the number of open connections would grow in a situation like stacklok's SaaS where a single minder instance can server many users and we could exhaust the number of fds available or just grow the memory a lot.

**Comment by Vyom-Yadav** [comment]
> Where/how were you thinking about caching the client, in the tokenStatusStore?

Yes, I was thinking of storing these clients in memory only. A bit different from tokenStatusStore, but yes, the same concept.

> One thing that sounds concerning to me is that if we were to cache the http clients globally as opposed to e.g. for a single evaluation of an entity, the number of open connections would grow in a situation like stacklok's SaaS where a single minder instance can server many users and we could exhaust the number of fds available or just grow the memory a lot.

That's a good concern, but we can do many things to get around it. 
- For instance, we could only cache rate limited clients instead of caching all clients, if a client gets rate limited cache it, and query cache before providing new clients to calling functions. 

- Secondly, we can have a max-age (1 hour looks good as tokens are hourly limited), and automatically prune them from the cache after they expire. We can have periodic expired clients removals (lazy), or we can start a timer for every cache entry and send a cache the deletion signal (eager).

- We can have size based eviction mechanism where if the size of cache reaches a certain threshold, we prune unused clients (user deleted) or even randomly delete clients to get below a certain threshold.

All these optimization should prevent us from exhausting server resources. Sounds good?

**Comment by Vyom-Yadav** [comment]
@jhrozek I implemented a pattern I think should work without hitting any bottleneck; please review it once. Thanks!

**Comment by jhrozek** [comment]
> @jhrozek I implemented a pattern I think should work without hitting any bottleneck; please review it once. Thanks!

Apologies for the delay. Last week, the whole Stacklok company was meeting in-person and the bandwidth for development was limited. I am looking at the code now.

File: internal/providers/ratecache/store.go [hunk 11]
```diff
@@ -0,0 +1,102 @@
...
+
+func (r *restClientCache) evictExpiredEntriesRoutine() {
+	timer := time.NewTimer(r.evictionTime)
+	defer timer.Stop()
+	for {
+		<-timer.C
+		r.evictExpiredEntries()
+
+		// Reset the timer for the next expiration
+		timer.Reset(r.evictionTime)
```
Comment (jhrozek) [inline internal/providers/ratecache/store.go:100]: I wonder if ticking once per eviction time is not too seldom. If a an entry is to be evicted just before a goroutine tick, this might mean that the entry will be in the cache for 30 more minutes. Do you think it would be useful to have the goroutine act more frequently, maybe twice per eviction time?

File: internal/providers/github/github.go [hunk 12]
```diff
@@ -115,3 +134,128 @@ func ParseV1Config(rawCfg json.RawMessage) (*minderv1.GitHubProviderConfig, erro
...
+		method = resp.Request.Method
+		path = resp.Request.URL.Path
+	}
+
+	logger.Debug().
+		Str("owner", owner).
+		Str("method", method).
+		Str("path", path).
+		Str("wait_time", waitTime.String()).
+		Msg("rate limit exceeded")
```
Comment (jhrozek) [inline internal/providers/github/github.go:244]: Do you think it might make sense to also log the two different rate limits (abuse vs primary) using a keyword (e.g. pass another parameter like "type" and set it one of two constant values)?

**Review by jhrozek — APPROVED** [review]
this is really nice code, great work.

I left a couple of comments, feel free to make another iteration or a follow up PR or reply if you disagree, but none of my comments are really blocking.

File: internal/providers/ratecache/store.go (hunk 11 above)
Comment (Vyom-Yadav) [reply internal/providers/ratecache/store.go]: Yes, it would be better to run the expired check using half the interval. Done.

File: internal/providers/github/github.go (hunk 12 above)
Comment (Vyom-Yadav) [reply internal/providers/github/github.go]: Yes, that would be better. Done.

**Comment by Vyom-Yadav** [comment]
@jhrozek When we use `defer ticker.Stop()`, it didn't free the underlying resources as the goroutine would have never got a chance to return, leading to a resource leak. I implemented a pattern with proper wait and context cancellation. Please check the new pattern.

**Review by jhrozek — APPROVED** [review]
LGTM!

File: cmd/server/app/serve.go [hunk 13]
```diff
@@ -176,6 +182,9 @@ var serveCmd = &cobra.Command{
 		// Wait for all entity events to be executed
 		exec.Wait()
 
+		// Wait for the client cache background routine to finish
+		restClientCache.Wait()
+
```
Comment (Vyom-Yadav) [inline cmd/server/app/serve.go:187]: @jhrozek Question: According to this logic, if the go routines above finish their execution (somehow, though it shouldn't happen for a server), this would mean the context has not been cancelled, and this would lead to an infinite wait as the ticker only stops using defer and context cancellation. 

On the other hand, the go routines started above should keep running as it's a server binary. In case of panic, the whole process would be stopped. Just double-checking, whether this is correct or not :)

**Review by JAORMX — APPROVED** [review]

**Comment by Vyom-Yadav** [comment]
@JAORMX I was addressing https://github.com/stacklok/minder/pull/2271#discussion_r1495557451 :)
I think that is incorrect `Wait()`. We want to free the ticker resources, so it would be better to do something like:
```go
func (r *restClientCache) Close() {
	r.evictionTicker.Stop()
}
```

**Comment by JAORMX** [comment]
@Vyom-Yadav let's do it in a subsequent PR. Thanks for all this work!
