### PR TITLE
Events of type "repository" now avoid checking hook id.

### LINKED ISSUE #3461: GitHub webhook events of type "repository" action "deleted" are not handled properly
### Describe the issue

Previous code handling repository deletion went through [this](https://github.com/stacklok/minder/blob/04db03c6784f80a3d47976e5dd443e3a8da4f03e/internal/controlplane/handlers_githubwebhooks.go#L531) line which evaluated to `false` and thus did not care about the hook id.

In its [current form](https://github.com/stacklok/minder/blob/main/internal/controlplane/handlers_githubwebhooks.go#L684), the check on the hook id is always performed (because we share the struct used to deserialize the JSON payload), while it does not make sense for events of type `repository`, as they do not contain any information about the hook (see [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads#repository)).

Ensure that [this check](https://github.com/stacklok/minder/blob/main/internal/controlplane/handlers_githubwebhooks.go#L684) is only performed on events of type `meta`.

### To Reproduce

1. register a repo
2. delete repo from github
3. this log line should occur
```
webhook event not handled (webhook event not handled: meta event with action deleted not handled, hook ID 0 does not match stored webhook ID 481299324)
```

### What version are you using?

_No response_

### PR DESCRIPTION
**Pull request by blkt**
# Summary

Events of type "repository" having "action" delete must trigger the deletion of registered repositories. Given we use the same deserialization struct for both "repository" and "meta" events, we erroneously checked the received hook id against the one stored in the database, thus consistently failing.

Added fix, test case, and improved logs.

Fixes #3461 

## Change Type

***Mark the type of change your PR introduces:***

- [X] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [X] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

* reproduced issue locally
* added test case

# Review Checklist:

- [X] Reviewed my own code for quality and clarity.
- [X] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [X] Included tests that validate the fix or feature.
- [X] Checked that related changes are merged.

### CODE REVIEW

File: internal/controlplane/handlers_githubwebhooks.go [hunk 1]
```diff
@@ -681,7 +697,7 @@ func (s *Server) processRelevantRepositoryEvent(
 	if dbrepo.WebhookID.Valid {
 		// Check if the payload webhook ID matches the one we
 		// have stored in the DB for this repository
-		if event.GetHookID() != dbrepo.WebhookID.Int64 {
+		if event.GetHookID() != 0 && event.GetHookID() != dbrepo.WebhookID.Int64 {
```
Comment (eleftherias) [inline internal/controlplane/handlers_githubwebhooks.go:700]: question: Does this fix work because the hook ID for repository events is always 0?

File: internal/controlplane/handlers_githubwebhooks.go [hunk 2]
```diff
@@ -681,7 +697,7 @@ func (s *Server) processRelevantRepositoryEvent(
 	if dbrepo.WebhookID.Valid {
 		// Check if the payload webhook ID matches the one we
```
Comment (eleftherias) [inline internal/controlplane/handlers_githubwebhooks.go:698]: question: Is the check for `event.GetHookID() != 0` better suited to be in this `if` statement?

Comment (blkt) [reply internal/controlplane/handlers_githubwebhooks.go:698]: You're right, I'll move it up.

File: internal/controlplane/handlers_githubwebhooks.go (hunk 1 above)
Comment (blkt) [reply internal/controlplane/handlers_githubwebhooks.go:700]: Yes, that's exactly the point.
The issue was not there before because we dynamically looked up `hook_id` using `jq`, while now we're using a shared struct to deserialize the messages and this makes it always get the default value.

Simply checking for it being some value other than `0` is sufficient and cannot cause bugs because it is not a valid value, and `go-github` handles deserialization in the same way as we do here, so we should be on the safe side.

**Review by evankanderson — APPROVED** [review]

File: internal/controlplane/handlers_githubwebhooks.go [hunk 3]
```diff
@@ -678,7 +694,7 @@ func (s *Server) processRelevantRepositoryEvent(
 	}
 
 	// This only makes sense for "meta" event type
-	if dbrepo.WebhookID.Valid {
+	if event.GetHookID() != 0 && dbrepo.WebhookID.Valid {
 		// Check if the payload webhook ID matches the one we
 		// have stored in the DB for this repository
 		if event.GetHookID() != dbrepo.WebhookID.Int64 {
```
Comment (evankanderson) [inline internal/controlplane/handlers_githubwebhooks.go:700]: Does the comment on line 701-703 still make sense?

**Review by evankanderson — COMMENTED** [review]
Oops, one more comment

File: internal/controlplane/handlers_githubwebhooks.go (hunk 3 above)
Comment (blkt) [reply internal/controlplane/handlers_githubwebhooks.go:700]: I think it does.

This routine is called only on `meta` and `repository` events, and this fix ensures that we check the hook id only when available, which is the case solely for the `meta` event.

The comment per sé is still valid, but can be removed if it's not useful.
I lean towards leaving it there for posterity, maybe rewriting it at the top of the `if`, but let me know.

**Review by eleftherias — APPROVED** [review]

File: internal/controlplane/handlers_githubwebhooks.go (hunk 3 above)
Comment (eleftherias) [reply internal/controlplane/handlers_githubwebhooks.go:700]: I agree that it's valid and useful
