### PR TITLE
User API: Add missing project display name and description

### LINKED ISSUE #3178: Users endpoint does not return `displayName` for projects
### Describe the issue

I noticed that in the /api/v1/user endpoint, the projects are returned with the same type as they are returned elsewhere (in the generated sdk it's called v1Project ), but the returned value here seems to be missing the displayName attribute. We actually want to display this value to the user. 

### To Reproduce

Should be enough to call the endpoint and observe the output. The user will need to have at least one project of course.

### What version are you using?

_No response_

### PR DESCRIPTION
**Pull request by puerco**
# Summary

This PR populates the missing descriptions and display names of projects included in the user API.

Fixes #3178

## Change Type

***Mark the type of change your PR introduces:***

- [x] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [ ] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

***Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.***

# Review Checklist:

- [x] Reviewed my own code for quality and clarity.
- [ ] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

File: internal/controlplane/handlers_user.go [hunk 1]
```diff
@@ -199,11 +200,21 @@ func (s *Server) getUserDependencies(ctx context.Context, user db.User) ([]*pb.P
 			return nil, err
 		}
 
+		// Try to parse the project metadata to complete the response fields
+		meta := &projects.Metadata{}
```
Comment (eleftherias) [inline internal/controlplane/handlers_user.go:204]: You could use `projects.ParseMetadata` here, instead of unmarshalling it yourself https://github.com/stacklok/minder/blob/main/internal/projects/meta.go#L66

Comment (puerco) [reply internal/controlplane/handlers_user.go]: Thanks for the tip @eleftherias ! Done :+1:

File: internal/controlplane/handlers_user.go [hunk 2]
```diff
@@ -199,11 +199,21 @@ func (s *Server) getUserDependencies(ctx context.Context, user db.User) ([]*pb.P
...
-			ProjectId: proj.String(),
-			Name:      pinfo.Name,
-			CreatedAt: timestamppb.New(pinfo.CreatedAt),
-			UpdatedAt: timestamppb.New(pinfo.UpdatedAt),
+			ProjectId:   proj.String(),
+			Name:        pinfo.Name,
+			CreatedAt:   timestamppb.New(pinfo.CreatedAt),
+			UpdatedAt:   timestamppb.New(pinfo.UpdatedAt),
+			DisplayName: pDisplay,
+			Description: pDescr,
```
Comment (rdimitrov) [inline internal/controlplane/handlers_user.go:216]: @kantord - hey, in case the parsing above fails for some reason is it okay with you to have the default variable values here, i.e. empty strings?

Comment (kantord) [reply internal/controlplane/handlers_user.go:216]: you mean specifically for description? I think for description, empty string is a reasonable fallback value, but for displayName I think that using the name as a fallback value would make more sense

Comment (kantord) [reply internal/controlplane/handlers_user.go:216]: also, I'm not very informed about how the BE codebase works, but as I understand the fallback logic happens at insertion time, meaning this code itself does not address existing data in the database. I guess those could be fixed using a database migration or a manual query?

Comment (evankanderson) [reply internal/controlplane/handlers_user.go:216]: I'm pretty sure this code is happening on the way _out_ of the database when answering the query, not on insertion.  (That's both what I would expect, and matches the pattern in the code where we're constructing a protocol buffer for output.)  If we change 203 to:

```golang
pDisplay := pinfo.Name
pDescr := ""
```

before calling `ParseMetadata`, that should be sufficient to fill in the defaults when the metadata doesn't exist in the database, without needing a backfill.

Comment (puerco) [reply internal/controlplane/handlers_user.go:217]: Thanks for the suggestion @evankanderson , I've changed the initial values as suggested :)

**Review by rdimitrov — APPROVED** [review]
